import type {
  CopyBlockId,
  CopyBlockRule,
  CopyDegradationRule,
  CopySectorRuleSet,
  CopyToneId,
  CopyValidationRule,
} from '../../types/copy-engine';

function blockRule(
  blockId: CopyBlockId,
  purpose: string,
  audienceIntent: string,
  tone: CopyToneId[],
  preferredInputs: string[],
  allowedProofTypes: CopyBlockRule['allowedProofTypes'],
  length: CopyBlockRule['length'],
  structure: string[],
  avoid: string[],
  forbiddenClaims: string[],
  degradationGuidance: string[],
  requiredSignals?: string[],
): CopyBlockRule {
  return {
    blockId,
    purpose,
    audienceIntent,
    tone,
    structure,
    preferredInputs,
    allowedProofTypes,
    avoid,
    forbiddenClaims,
    length,
    degradationGuidance,
    requiredSignals,
  };
}

const GLOBAL_FORBIDDEN_CLAIMS = [
  'Do not invent hours, prices, offers, awards, lead times, or reservation support.',
  'Do not claim a website, order flow, email route, or WhatsApp route unless verified.',
  'Do not use unverified superlatives like best, leading, number one, or award-winning.',
  'Do not fabricate team names, certifications, or years in business.',
];

const BASE_VALIDATION_RULES: CopyValidationRule[] = [
  {
    id: 'length-limits',
    description: 'Each block should respect its configured word and character limits.',
    appliesTo: [
      'hero-title',
      'hero-subheadline',
      'hero-support',
      'cta-primary',
      'cta-secondary',
      'highlights',
      'trust-summary',
      'review-signals',
      'gallery-support',
      'location-contact',
      'faq',
      'final-cta',
      'footer',
    ],
    severity: 'warning',
  },
  {
    id: 'no-fabricated-claims',
    description: 'Copy must not imply unverified hours, prices, offers, awards, or booking capabilities.',
    appliesTo: [
      'hero-title',
      'hero-subheadline',
      'hero-support',
      'trust-summary',
      'location-contact',
      'faq',
      'final-cta',
      'footer',
    ],
    severity: 'error',
  },
  {
    id: 'avoid-empty-decoration',
    description: 'Copy should avoid vague decorative language with no factual anchor.',
    appliesTo: ['hero-title', 'hero-subheadline', 'highlights', 'trust-summary', 'gallery-support', 'final-cta'],
    severity: 'hint',
  },
  {
    id: 'avoid-duplicate-cta-language',
    description: 'CTA labels and supporting lines should not repeat the same action point excessively.',
    appliesTo: ['cta-primary', 'cta-secondary', 'final-cta'],
    severity: 'warning',
  },
  {
    id: 'faq-needs-real-utility',
    description: 'FAQ should answer practical questions with short, real answers, or stay absent.',
    appliesTo: ['faq'],
    severity: 'warning',
  },
];

const RESTAURANT_BLOCK_RULES: CopyBlockRule[] = [
  blockRule(
    'hero-title',
    'State cuisine, standout cue, and local context fast.',
    'Decide in a few seconds whether this is worth visiting or trying.',
    ['warm-food-led', 'premium-casual', 'local-trust'],
    ['identity.primaryCategory', 'brand.tagline', 'location.city', 'offer.featuredItems'],
    ['facts', 'offer', 'location'],
    { maxWords: 12, maxChars: 78, maxSentences: 1 },
    ['Lead with cuisine or standout dish cue.', 'Keep the sentence concrete and local.', 'Avoid stacked adjectives.'],
    ['generic lifestyle language', 'empty premium wording', 'multiple claims in one line'],
    ['best in town', 'award-winning', 'authentic if not verified', 'open late if hours are missing'],
    ['If offer data is thin, keep the hero local and cuisine-led.', 'If order flow is missing, do not make the hero order-first.'],
  ),
  blockRule(
    'hero-subheadline',
    'Explain what the place offers and the practical next step.',
    'Understand service modes and whether the business is easy to visit.',
    ['premium-casual', 'local-trust', 'direct-conversion'],
    ['brand.shortDescription', 'offer.serviceModes', 'location.city'],
    ['facts', 'offer', 'location'],
    { maxWords: 22, maxChars: 140, maxSentences: 2 },
    ['Name the place type or signature.', 'Mention one practical service or visit cue.', 'Keep it easy to scan.'],
    ['too much mood writing', 'duplicating the headline word for word'],
    ['delivery promise if not confirmed', 'website route if missing', 'reservation support if not verified'],
    ['If service modes are missing, keep the line focused on location and category only.'],
  ),
  blockRule(
    'hero-support',
    'Add one useful, appetite-led support line under the hero.',
    'Get a quick feel for why the business is worth trying.',
    ['warm-food-led', 'premium-casual'],
    ['brand.heroSignature', 'trust.reviewHighlights', 'offer.featuredItems'],
    ['offer', 'review-themes', 'facts'],
    { maxWords: 18, maxChars: 120, maxSentences: 1 },
    ['Use one strong detail.', 'Keep it human and specific.'],
    ['abstract brand manifestos', 'repeating headline and subheadline'],
    ['guaranteed quality', 'famous', 'best-loved'],
    ['If standout dish data is weak, use local trust instead of hype.'],
  ),
  blockRule(
    'cta-primary',
    'Turn the clearest verified action into a short button label.',
    'Know the next step without thinking.',
    ['direct-conversion', 'local-trust'],
    ['contentPlan.primaryCta.label', 'sectorProfile.recommendedPrimaryCta'],
    ['facts', 'location'],
    { maxWords: 3, maxChars: 18, maxSentences: 1 },
    ['Prefer action-first labels.', 'Keep buttons short and literal.'],
    ['cute CTA labels', 'button copy that explains too much'],
    ['order online if no order URL', 'book now if no booking flow'],
    ['If the ideal CTA is unavailable, degrade to the strongest truthful action.'],
  ),
  blockRule(
    'cta-secondary',
    'Support the main action without creating decision fatigue.',
    'Keep a backup path close by.',
    ['direct-conversion', 'local-trust'],
    ['contentPlan.secondaryCtas', 'sectorProfile.recommendedSecondaryCtas'],
    ['facts', 'location', 'offer'],
    { maxWords: 3, maxChars: 18, maxSentences: 1, maxItems: 2 },
    ['Use literal action labels.', 'Do not repeat the primary CTA verb unless necessary.'],
    ['more than two visible secondary actions', 'soft labels with unclear outcome'],
    ['website CTA if no site exists', 'delivery CTA if route is not verified'],
    ['If options are weak, keep one secondary action only.'],
  ),
  blockRule(
    'highlights',
    'Describe dishes, services, or products in a way that helps selection.',
    'Understand what is worth trying without reading a menu wall.',
    ['warm-food-led', 'premium-casual', 'direct-conversion'],
    ['offer.featuredItems', 'offer.services'],
    ['offer', 'facts'],
    { maxWords: 18, maxChars: 110, maxSentences: 2 },
    ['Start with the item or category.', 'Use one practical descriptor.', 'Keep summaries specific and short.'],
    ['poetic filler', 'overexplaining ingredients when unverified', 'same sentence pattern for every card'],
    ['signature if not evidenced', 'spicy/hot level if not confirmed', 'pricing if not confirmed'],
    ['If menu detail is light, talk about what the item helps the visitor choose, not hidden specifics.'],
  ),
  blockRule(
    'trust-summary',
    'Summarize trust using the strongest real proof available.',
    'Feel safe trying the place.',
    ['local-trust', 'direct-conversion'],
    ['trust.ratingValue', 'trust.reviewCount', 'trust.reviewHighlights', 'trust.proofPoints'],
    ['ratings', 'review-themes', 'facts'],
    { maxWords: 24, maxChars: 150, maxSentences: 2 },
    ['Use numbers if verified.', 'Summarize review themes plainly.', 'Keep the tone credible, not overexcited.'],
    ['generic hype', 'trying to sound like an ad testimonial'],
    ['customers love us if no review basis', 'five-star if actual rating differs'],
    ['If no testimonials exist, summarize themes instead of inventing quoted voices.'],
  ),
  blockRule(
    'review-signals',
    'List short, repeated themes from reviews or proof points.',
    'Scan proof quickly.',
    ['local-trust', 'direct-conversion'],
    ['trust.reviewHighlights', 'trust.proofPoints'],
    ['review-themes', 'facts'],
    { maxWords: 5, maxChars: 36, maxItems: 4 },
    ['Use short fragments.', 'Keep each point distinct.', 'Prefer nouns and clear attributes.'],
    ['full sentences', 'repeating the same concept with different words'],
    ['invented testimonial quotes'],
    ['If review themes are weak, reduce the list rather than padding it.'],
  ),
  blockRule(
    'gallery-support',
    'Frame the gallery with one honest line.',
    'Understand what the images are meant to prove.',
    ['warm-food-led', 'premium-casual'],
    ['visualProfile.family.gallery', 'brand.photographyStyle', 'contentPlan.messaging.galleryFocus'],
    ['visual-cues', 'facts'],
    { maxWords: 14, maxChars: 90, maxSentences: 1 },
    ['Use one image-led idea.', 'Support the visuals instead of narrating them.'],
    ['mood-board copy', 'saying the same thing as the hero again'],
    ['storefront reference if no exterior image', 'luxury atmosphere if not supported'],
    ['If imagery is sparse, use a simpler support line and reduce gallery ambition.'],
  ),
  blockRule(
    'location-contact',
    'Make address, phone, hours, and visit cues easy to act on.',
    'Know where to go and how to reach the business.',
    ['local-trust', 'direct-conversion'],
    ['location.addressLine', 'contact.phone', 'operations.openingHours', 'contentPlan.messaging.locationFocus'],
    ['location', 'facts'],
    { maxWords: 22, maxChars: 150, maxSentences: 2 },
    ['Lead with the practical visit value.', 'Do not restate the full address multiple times in the same block.'],
    ['fluffy closing language', 'repeating phone/address in every sentence'],
    ['open now when hours missing', 'walk-ins welcome if not verified'],
    ['If hours are missing, say directions and call are available, not that the place is open.'],
  ),
  blockRule(
    'faq',
    'Answer the most likely practical questions briefly.',
    'Resolve first-visit friction without bloating the page.',
    ['local-trust', 'direct-conversion'],
    ['offer.faqItems', 'offer.serviceModes', 'location.addressLine'],
    ['facts', 'offer', 'location'],
    { maxWords: 26, maxChars: 180, maxSentences: 2, maxItems: 3 },
    ['Questions should be real customer questions.', 'Answers should be short, direct, and factual.'],
    ['FAQ as filler', 'generic hospitality copy', 'overlong answers'],
    ['hours if missing', 'reservation policy if not verified', 'team references if absent'],
    ['If no practical questions exist, reduce FAQ count or suppress the block.'],
  ),
  blockRule(
    'final-cta',
    'Close with the strongest truthful next step and one calm line of reassurance.',
    'Take action after scanning the page.',
    ['direct-conversion', 'local-trust'],
    ['contentPlan.primaryCta', 'sectorProfile.recommendedPrimaryCta', 'contentPlan.messaging.locationFocus'],
    ['facts', 'location', 'offer'],
    { maxWords: 18, maxChars: 120, maxSentences: 1 },
    ['Use a practical close.', 'Avoid sounding more urgent than the business can support.'],
    ['repeating the hero verbatim', 'multiple urgent commands'],
    ['order now if order flow is absent', 'book today if no booking route exists'],
    ['If only one strong action exists, let the close be softer and more location-led.'],
  ),
  blockRule(
    'footer',
    'Reinforce category, locality, and one practical trust cue.',
    'End with orientation, not noise.',
    ['local-trust', 'direct-conversion'],
    ['identity.primaryCategory', 'location.city', 'trust.ratingValue', 'offer.serviceModes'],
    ['facts', 'location', 'ratings'],
    { maxWords: 16, maxChars: 100, maxSentences: 1 },
    ['Keep it simple.', 'Use one factual summary line only.'],
    ['marketing tagline repetition', 'selling language in the footer'],
    ['unverified awards', 'hours if missing'],
    ['If proof is thin, keep the footer to category + location only.'],
  ),
];

const RESTAURANT_DEGRADATIONS: CopyDegradationRule[] = [
  {
    id: 'copy-no-order-url',
    whenMissingPaths: ['contact.orderUrl'],
    guidance: 'Keep the copy visit-led or menu-led when no verified order flow exists.',
    affectedBlocks: ['hero-title', 'hero-subheadline', 'cta-primary', 'cta-secondary', 'final-cta'],
    adjustments: ['prefer directions over ordering', 'avoid delivery-first claims', 'keep CTA literal'],
  },
  {
    id: 'copy-no-menu-url',
    whenMissingPaths: ['contact.menuUrl'],
    guidance: 'Talk about menu highlights on-page instead of implying a complete external menu.',
    affectedBlocks: ['highlights', 'cta-secondary', 'final-cta'],
    adjustments: ['frame menu as highlights', 'avoid full menu language'],
  },
  {
    id: 'copy-no-hours',
    whenMissingPaths: ['location.openingHours'],
    guidance: 'Do not mention open-now, opening windows, or easy late-night availability.',
    affectedBlocks: ['hero-subheadline', 'location-contact', 'faq', 'footer'],
    adjustments: ['stick to address and call cues', 'avoid time-based wording'],
  },
  {
    id: 'copy-no-testimonials',
    whenMissingPaths: ['trust.testimonials'],
    guidance: 'Summarize review themes instead of writing quote-style proof.',
    affectedBlocks: ['trust-summary', 'review-signals'],
    adjustments: ['use review themes', 'avoid quotation marks'],
  },
];

const RESTAURANT_RULE_SET: CopySectorRuleSet = {
  sectorType: 'restaurant',
  label: 'Restaurant / Food Copy',
  description: 'Designed for food businesses that need appetite, local trust, and one truthful next step.',
  tonePriority: ['warm-food-led', 'premium-casual', 'local-trust', 'direct-conversion'],
  heroFocus: 'Cuisine + standout item + local context',
  closingStyle: 'Practical, visit-led, and calm rather than shouty.',
  trustPriority: ['rating-reviews', 'menu-signatures', 'local-trust'],
  allowedClaims: [
    'Verified rating and review count',
    'Verified service modes',
    'Verified location and local context',
    'Known review themes grounded in current source set',
    'Named featured dishes or offer categories that exist in the brief',
  ],
  forbiddenClaims: [...GLOBAL_FORBIDDEN_CLAIMS, 'Do not promise online ordering, reservations, or a full menu URL when those routes are missing.'],
  blockRules: RESTAURANT_BLOCK_RULES,
  degradationRules: RESTAURANT_DEGRADATIONS,
};

const GENERIC_SERVICE_RULES: CopySectorRuleSet = {
  sectorType: 'local-service',
  label: 'Local Service Copy',
  description: 'Practical copy rules for local service businesses where clarity and contact matter most.',
  tonePriority: ['local-trust', 'direct-conversion', 'modern-clean'],
  heroFocus: 'What the business does + where it helps + clear action',
  closingStyle: 'Direct and useful, with low hype.',
  trustPriority: ['rating-reviews', 'local-trust', 'years-in-business'],
  allowedClaims: [
    'Verified service scope',
    'Verified location or service area',
    'Verified contact methods',
    'Verified review themes or rating proof',
  ],
  forbiddenClaims: [...GLOBAL_FORBIDDEN_CLAIMS, 'Do not promise response times, same-day support, or availability windows unless confirmed.'],
  blockRules: [
    blockRule(
      'hero-title',
      'State the service and who it is for quickly.',
      'Decide whether the business solves the user problem.',
      ['local-trust', 'direct-conversion', 'modern-clean'],
      ['identity.primaryCategory', 'brand.tagline', 'location.city'],
      ['facts', 'location', 'offer'],
      { maxWords: 11, maxChars: 72, maxSentences: 1 },
      ['Lead with the service promise.', 'Keep it concrete and local.'],
      ['brand theater', 'generic mission language'],
      ['fastest', 'best', 'same-day', '24/7 unless verified'],
      ['If specifics are weak, prefer clarity over personality.'],
    ),
    blockRule(
      'hero-subheadline',
      'Explain the practical value and the best next step.',
      'Understand the route to contact or visit.',
      ['local-trust', 'direct-conversion'],
      ['brand.shortDescription', 'contentPlan.conversionFocus', 'location.city'],
      ['facts', 'location', 'offer'],
      { maxWords: 22, maxChars: 140, maxSentences: 2 },
      ['Mention one service benefit and one action route.'],
      ['too much tone decoration'],
      ['booking path if not verified', 'email route if missing'],
      ['If actions are limited, make the line more local and practical.'],
    ),
  ],
  degradationRules: [
    {
      id: 'service-no-website',
      whenMissingPaths: ['contact.website'],
      guidance: 'Keep contact copy call-led or visit-led when no website exists.',
      affectedBlocks: ['hero-subheadline', 'cta-primary', 'final-cta'],
      adjustments: ['avoid website verbs', 'prefer call or directions'],
    },
  ],
};

const CLINIC_RULES: CopySectorRuleSet = {
  ...GENERIC_SERVICE_RULES,
  sectorType: 'clinic-health',
  label: 'Clinic / Health Copy',
  description: 'Calm, clear, low-hype copy for clinics and health-led services.',
  tonePriority: ['calm-clinical', 'direct-conversion', 'local-trust'],
  heroFocus: 'Service clarity + reassurance + safe action',
  closingStyle: 'Calm and responsible, with no pressure tactics.',
  trustPriority: ['staff-credentials', 'certifications', 'rating-reviews'],
  forbiddenClaims: [...GLOBAL_FORBIDDEN_CLAIMS, 'Do not imply medical urgency, specialist status, or treatment outcomes unless verified.'],
};

const PERSONAL_CARE_RULES: CopySectorRuleSet = {
  ...GENERIC_SERVICE_RULES,
  sectorType: 'personal-care',
  label: 'Personal Care Copy',
  description: 'Clear service-led copy for barber, grooming, beauty, and personal care businesses.',
  tonePriority: ['boutique-service', 'modern-clean', 'direct-conversion', 'local-trust'],
  heroFocus: 'Service result + local trust + booking clarity',
  closingStyle: 'Confident and clear, without overselling.',
};

const RETAIL_RULES: CopySectorRuleSet = {
  ...GENERIC_SERVICE_RULES,
  sectorType: 'retail-shop',
  label: 'Retail Copy',
  description: 'Controlled, product-first copy for shops and boutiques.',
  tonePriority: ['modern-clean', 'boutique-service', 'direct-conversion'],
  heroFocus: 'What you can browse or buy + why the store is worth visiting',
  closingStyle: 'Browse-or-visit, not hard sell.',
  forbiddenClaims: [...GLOBAL_FORBIDDEN_CLAIMS, 'Do not imply online catalog depth, stock levels, or ecommerce support unless verified.'],
};

const FITNESS_RULES: CopySectorRuleSet = {
  ...GENERIC_SERVICE_RULES,
  sectorType: 'fitness-wellness',
  label: 'Fitness / Wellness Copy',
  description: 'Clear, motivating, non-hype copy for gyms, studios, and wellness operators.',
  tonePriority: ['direct-conversion', 'modern-clean', 'local-trust'],
  heroFocus: 'Program or benefit + first step + confidence signal',
  closingStyle: 'Encouraging but grounded.',
  forbiddenClaims: [...GLOBAL_FORBIDDEN_CLAIMS, 'Do not promise results, transformations, or class availability unless verified.'],
};

const CAFE_RULES: CopySectorRuleSet = {
  ...RESTAURANT_RULE_SET,
  sectorType: 'cafe-bakery-takeaway',
  label: 'Cafe / Bakery Copy',
  description: 'Shorter, faster food and visit copy for cafes, bakeries, and takeaway businesses.',
  heroFocus: 'Quick-stop product cue + locality + easy visit',
  closingStyle: 'Easy, practical, and friendly.',
};

export const COPY_SECTOR_RULES: Record<CopySectorRuleSet['sectorType'], CopySectorRuleSet> = {
  restaurant: RESTAURANT_RULE_SET,
  'cafe-bakery-takeaway': CAFE_RULES,
  'personal-care': PERSONAL_CARE_RULES,
  'retail-shop': RETAIL_RULES,
  'fitness-wellness': FITNESS_RULES,
  'clinic-health': CLINIC_RULES,
  'local-service': GENERIC_SERVICE_RULES,
};

export const COPY_VALIDATION_RULES = BASE_VALIDATION_RULES;

export const TONE_PREFERENCES: Record<CopyToneId, string> = {
  'warm-food-led': 'Use vivid but concrete food-led language anchored to real dishes, locality, and practical next steps.',
  'premium-casual': 'Sound polished and edited, not stiff or ornate.',
  'local-trust': 'Use grounded, truthful, place-aware language that makes the business feel reliable nearby.',
  'modern-clean': 'Use crisp, uncluttered sentences with low fluff and strong hierarchy.',
  'calm-clinical': 'Use measured, reassuring, low-drama language with high clarity.',
  'boutique-service': 'Sound selective and premium without becoming precious or vague.',
  'direct-conversion': 'Make the next step obvious and reduce friction without sounding pushy.',
};
