import type {
  SectorRuleSet,
  SectorSectionId,
  SectorType,
} from '../../types/sector-engine';

function section(
  id: SectorSectionId,
  priority: 'high' | 'medium' | 'low',
  reason: string,
  currentSystemSectionId?: string | null,
) {
  return {
    id,
    priority,
    reason,
    currentSystemSectionId: currentSystemSectionId ?? null,
  };
}

export const SECTOR_RULES: Record<SectorType, SectorRuleSet> = {
  restaurant: {
    sectorType: 'restaurant',
    label: 'Restaurant / Food Business',
    description: 'Built for dine-in, takeaway, and delivery-led food businesses where menu appetite and local trust matter first.',
    nicheSignals: ['restaurant'],
    categoryKeywords: ['restaurant', 'food', 'indian', 'dosa', 'takeaway', 'grill', 'kitchen', 'eatery'],
    serviceModeKeywords: ['dine-in', 'delivery', 'pickup', 'takeaway'],
    offerKeywords: ['menu', 'dish', 'dessert', 'starter', 'curry', 'plate', 'dosa', 'meal'],
    imageSignals: ['image:dish', 'image:ambience'],
    primaryCtaPriority: ['order-online', 'get-directions', 'view-menu', 'call'],
    secondaryCtaPriority: ['view-menu', 'call', 'get-directions', 'visit-website'],
    conversionFocus: 'Move the user quickly from appetite and trust into ordering, visiting, or checking the menu.',
    recommendedHeroType: 'food-first',
    recommendedSections: [
      section('hero', 'high', 'Lead with cuisine, locality, and one real food cue.', 'hero'),
      section('signature-items', 'high', 'Show one or two standout dishes early.', 'popular-items'),
      section('menu-highlights', 'high', 'Let users scan offer breadth without a full menu wall.', 'services'),
      section('trust', 'high', 'Rating and review proof should validate the choice fast.', 'credibility'),
      section('gallery', 'medium', 'Support appetite and atmosphere with a tight image set.', 'gallery'),
      section('faq', 'medium', 'Resolve first-visit questions around ordering modes and location.', 'faq'),
      section('location-contact', 'high', 'Directions, phone, and address need to be easy to reach.', 'cta'),
      section('cta', 'high', 'Close with the strongest truthful next step.', 'cta'),
      section('footer', 'low', 'Reinforce local trust and contact details.', 'footer'),
    ],
    recommendedTrustSystems: ['rating-reviews', 'menu-signatures', 'local-trust'],
    recommendedGallerySystems: ['dishes', 'ambience', 'exterior'],
    recommendedTone: ['premium-casual', 'warm', 'local-trust', 'direct'],
    degradationRules: [
      {
        id: 'restaurant-no-order-link',
        whenMissingPaths: ['contact.orderUrl'],
        whenUnavailableActions: ['order-online'],
        guidance: 'Do not lead with ordering when no verified order route exists. Shift to directions or menu exploration.',
        suppress: ['order-led hero copy', 'delivery-first framing'],
        fallbackActions: ['get-directions', 'view-menu', 'call'],
      },
      {
        id: 'restaurant-no-menu-url',
        whenMissingPaths: ['contact.menuUrl'],
        guidance: 'Keep menu language anchored to on-page highlights and avoid implying a full verified external menu.',
        suppress: ['external menu claims'],
        fallbackActions: ['view-menu', 'get-directions'],
      },
      {
        id: 'restaurant-no-hours',
        whenMissingPaths: ['location.openingHours'],
        guidance: 'Do not promise open-now convenience or late-service claims until hours are verified.',
        suppress: ['open now messaging', 'time-sensitive claims'],
        fallbackActions: ['get-directions', 'call'],
      },
      {
        id: 'restaurant-no-exterior',
        whenMissingSignals: ['image:exterior'],
        guidance: 'If no exterior image exists, keep the gallery food-first and let maps carry location trust.',
        suppress: ['storefront-led gallery'],
        fallbackActions: ['get-directions'],
      },
    ],
    schemaHints: {
      preferredSchemaTypes: ['Restaurant', 'FoodEstablishment', 'LocalBusiness'],
      prioritySignals: ['NAP consistency', 'servesCuisine', 'opening hours', 'menu URL', 'review count', 'service area'],
      keywordPatterns: ['[cuisine] restaurant [city]', '[signature dish] [city]', '[street] food [city]'],
      doNotInvent: ['delivery radius', 'opening hours', 'price range', 'online ordering', 'reservation support'],
    },
  },
  'cafe-bakery-takeaway': {
    sectorType: 'cafe-bakery-takeaway',
    label: 'Cafe / Bakery / Takeaway',
    description: 'Optimized for coffee, pastry, brunch, bakery, and quick-stop food businesses.',
    categoryKeywords: ['cafe', 'coffee', 'bakery', 'pastry', 'bakehouse', 'espresso', 'sandwich', 'takeaway'],
    serviceModeKeywords: ['takeaway', 'pickup', 'delivery', 'walk-in'],
    offerKeywords: ['coffee', 'pastry', 'cake', 'sandwich', 'bake', 'brunch', 'menu'],
    imageSignals: ['image:dish', 'image:product', 'image:ambience'],
    primaryCtaPriority: ['get-directions', 'view-menu', 'order-online', 'call'],
    secondaryCtaPriority: ['view-menu', 'order-online', 'call', 'visit-website'],
    conversionFocus: 'Get the user to stop by, browse the offer quickly, or place a lightweight order if supported.',
    recommendedHeroType: 'food-first',
    recommendedSections: [
      section('hero', 'high', 'Make the first screen feel easy, local, and appetite-led.', 'hero'),
      section('signature-items', 'high', 'Lead with the most photogenic or most-ordered items.', 'popular-items'),
      section('menu-highlights', 'medium', 'Surface drink, pastry, or takeaway cues without overloading.', 'services'),
      section('trust', 'medium', 'Reviews and local repeat-visit cues matter more than heavy proof stacks.', 'credibility'),
      section('gallery', 'medium', 'Gallery should mix products with atmosphere.', 'gallery'),
      section('location-contact', 'high', 'Quick-stop businesses need easy visit info.', 'cta'),
      section('cta', 'high', 'Keep the close practical and low-friction.', 'cta'),
      section('footer', 'low', 'Footer should repeat essentials cleanly.', 'footer'),
    ],
    recommendedTrustSystems: ['rating-reviews', 'product-quality', 'local-trust'],
    recommendedGallerySystems: ['products', 'ambience', 'exterior'],
    recommendedTone: ['warm', 'friendly', 'modern-clean', 'direct'],
    degradationRules: [
      {
        id: 'cafe-no-menu',
        whenMissingPaths: ['contact.menuUrl'],
        guidance: 'Keep the offer curated on-page and avoid promising a complete menu if one is not verified.',
        suppress: ['full-menu promises'],
        fallbackActions: ['get-directions', 'call'],
      },
      {
        id: 'cafe-no-order',
        whenMissingPaths: ['contact.orderUrl'],
        whenUnavailableActions: ['order-online'],
        guidance: 'If no order flow is verified, pivot to directions and in-person pickup framing.',
        suppress: ['checkout language'],
        fallbackActions: ['get-directions', 'view-menu'],
      },
      {
        id: 'cafe-light-images',
        whenMissingSignals: ['image:product'],
        guidance: 'If product photography is weak, keep the gallery tight and rely more on atmosphere and locality.',
        suppress: ['grid-heavy product gallery'],
        fallbackActions: ['get-directions'],
      },
    ],
    schemaHints: {
      preferredSchemaTypes: ['CafeOrCoffeeShop', 'Bakery', 'LocalBusiness'],
      prioritySignals: ['NAP consistency', 'opening hours', 'menu URL', 'review signals', 'service area'],
      keywordPatterns: ['[category] [city]', '[product] [city]', '[street] coffee [city]'],
      doNotInvent: ['delivery support', 'online ordering', 'opening hours', 'signature products'],
    },
  },
  'personal-care': {
    sectorType: 'personal-care',
    label: 'Barber / Beauty / Personal Care',
    description: 'Focused on appointment, grooming, beauty, and personal service businesses where service clarity matters most.',
    nicheSignals: ['barbershop'],
    categoryKeywords: ['barber', 'barbershop', 'salon', 'beauty', 'hair', 'grooming', 'spa', 'lashes', 'nails'],
    serviceModeKeywords: ['appointment', 'walk-in'],
    offerKeywords: ['haircut', 'fade', 'beard', 'style', 'trim', 'facial', 'treatment'],
    imageSignals: ['image:team', 'image:results', 'image:space'],
    primaryCtaPriority: ['book-appointment', 'call', 'get-directions', 'visit-website'],
    secondaryCtaPriority: ['get-directions', 'call', 'visit-website', 'request-consultation'],
    conversionFocus: 'Push the clearest booking or contact route, backed by service clarity and trust cues.',
    recommendedHeroType: 'service-first',
    recommendedSections: [
      section('hero', 'high', 'State the service promise and location immediately.', 'hero'),
      section('services', 'high', 'Users need a fast service scan before they commit.', 'services'),
      section('team', 'medium', 'Team or specialist visibility helps reduce hesitation.'),
      section('trust', 'high', 'Reviews and service proof do heavy lifting.', 'credibility'),
      section('gallery', 'medium', 'Use service results, team, and space selectively.', 'gallery'),
      section('faq', 'medium', 'FAQ helps with booking friction, walk-ins, and expectations.', 'faq'),
      section('booking', 'high', 'Booking or fallback contact needs dedicated emphasis.', 'cta'),
      section('location-contact', 'medium', 'Directions still matter for local repeat business.', 'cta'),
      section('cta', 'high', 'Close on the strongest truthful appointment route.', 'cta'),
      section('footer', 'low', 'Repeat contact and local reassurance.', 'footer'),
    ],
    recommendedTrustSystems: ['rating-reviews', 'service-results', 'years-in-business', 'local-trust'],
    recommendedGallerySystems: ['service-results', 'team', 'spaces', 'exterior'],
    recommendedTone: ['modern-clean', 'boutique', 'friendly', 'direct'],
    degradationRules: [
      {
        id: 'care-no-booking-link',
        whenUnavailableActions: ['book-appointment'],
        guidance: 'If booking is not verified, fall back to call or directions instead of implying an appointment flow.',
        suppress: ['book instantly claims', 'calendar language'],
        fallbackActions: ['call', 'get-directions', 'visit-website'],
      },
      {
        id: 'care-no-team',
        whenMissingSignals: ['image:team'],
        guidance: 'Do not imply a named team or specialist roster if no team material is available.',
        suppress: ['meet the team blocks', 'named stylist cards'],
        fallbackActions: ['call'],
      },
      {
        id: 'care-no-results',
        whenMissingSignals: ['image:results'],
        guidance: 'If before/after or service-result imagery is not available, lean on reviews and space quality instead.',
        suppress: ['transformation-led gallery'],
        fallbackActions: ['get-directions', 'call'],
      },
    ],
    schemaHints: {
      preferredSchemaTypes: ['HairSalon', 'BeautySalon', 'LocalBusiness'],
      prioritySignals: ['service list', 'booking route', 'opening hours', 'NAP consistency', 'review signals'],
      keywordPatterns: ['[service] [city]', '[category] [city]', '[neighborhood] barber [city]'],
      doNotInvent: ['walk-in policy', 'booking support', 'staff count', 'specialist credentials'],
    },
  },
  'retail-shop': {
    sectorType: 'retail-shop',
    label: 'Retail / Shop',
    description: 'Built for local shops and boutiques where product discovery and physical visit intent need to work together.',
    categoryKeywords: ['shop', 'store', 'retail', 'boutique', 'florist', 'gifts', 'fashion', 'homeware'],
    offerKeywords: ['product', 'collection', 'gift', 'brand', 'shop', 'item'],
    imageSignals: ['image:product', 'image:space', 'image:exterior'],
    primaryCtaPriority: ['browse-products', 'get-directions', 'visit-website', 'call'],
    secondaryCtaPriority: ['get-directions', 'visit-website', 'call', 'request-consultation'],
    conversionFocus: 'Help the user browse the product promise quickly, then move them toward visiting or checking the storefront online.',
    recommendedHeroType: 'product-first',
    recommendedSections: [
      section('hero', 'high', 'Lead with the product promise and store identity.', 'hero'),
      section('products', 'high', 'A retail page needs a clear product route early.'),
      section('trust', 'medium', 'Use review or quality cues to support buying confidence.', 'credibility'),
      section('gallery', 'medium', 'Gallery should show products and the store environment.', 'gallery'),
      section('faq', 'low', 'Only use FAQ if it answers pickup, stock, or visit questions.', 'faq'),
      section('location-contact', 'high', 'Local shops still depend heavily on directions.', 'cta'),
      section('cta', 'high', 'Close with the cleanest browse-or-visit action.', 'cta'),
      section('footer', 'low', 'Repeat practical store details.', 'footer'),
    ],
    recommendedTrustSystems: ['product-quality', 'rating-reviews', 'local-trust', 'years-in-business'],
    recommendedGallerySystems: ['products', 'spaces', 'exterior'],
    recommendedTone: ['boutique', 'modern-clean', 'direct', 'friendly'],
    degradationRules: [
      {
        id: 'retail-no-catalog',
        whenUnavailableActions: ['browse-products'],
        guidance: 'If no verified product browsing path exists, keep the page local and visit-led instead of implying ecommerce.',
        suppress: ['shop now language', 'catalog promises'],
        fallbackActions: ['get-directions', 'visit-website', 'call'],
      },
      {
        id: 'retail-light-product-images',
        whenMissingSignals: ['image:product'],
        guidance: 'If product imagery is weak, keep the gallery sparse and let local trust and store presence do more work.',
        suppress: ['large product grids'],
        fallbackActions: ['get-directions'],
      },
      {
        id: 'retail-no-website',
        whenMissingPaths: ['contact.website'],
        guidance: 'Do not imply online browsing if the store does not have a verified web route.',
        suppress: ['browse online framing'],
        fallbackActions: ['get-directions', 'call'],
      },
    ],
    schemaHints: {
      preferredSchemaTypes: ['Store', 'ClothingStore', 'Florist', 'LocalBusiness'],
      prioritySignals: ['NAP consistency', 'opening hours', 'brand or category keywords', 'review signals', 'website presence'],
      keywordPatterns: ['[category] shop [city]', '[product] [city]', '[street] boutique [city]'],
      doNotInvent: ['inventory availability', 'online checkout', 'brand stock', 'price range'],
    },
  },
  'fitness-wellness': {
    sectorType: 'fitness-wellness',
    label: 'Gym / Fitness / Wellness',
    description: 'Built for gyms, studios, training spaces, and wellness operators where trust and program clarity drive action.',
    categoryKeywords: ['gym', 'fitness', 'pilates', 'yoga', 'training', 'wellness', 'studio', 'coach'],
    offerKeywords: ['class', 'membership', 'training', 'session', 'coaching', 'recovery'],
    imageSignals: ['image:results', 'image:team', 'image:space'],
    primaryCtaPriority: ['request-consultation', 'book-appointment', 'call', 'get-directions'],
    secondaryCtaPriority: ['get-directions', 'call', 'visit-website', 'request-consultation'],
    conversionFocus: 'Push users toward consultation, class interest, or a first visit without overpromising schedule or availability.',
    recommendedHeroType: 'transformation-first',
    recommendedSections: [
      section('hero', 'high', 'State the training or wellness promise clearly.', 'hero'),
      section('services', 'high', 'Programs, classes, or packages need a fast scan route.', 'services'),
      section('trust', 'high', 'Credentials, outcomes, or strong review proof should show early.', 'credibility'),
      section('results', 'medium', 'Transformation or outcome proof matters if it is real.'),
      section('team', 'medium', 'Coach or practitioner presence reduces uncertainty.'),
      section('gallery', 'medium', 'Gallery should show spaces, people, and believable outcomes.', 'gallery'),
      section('faq', 'medium', 'FAQ helps with trial expectations and practical questions.', 'faq'),
      section('booking', 'high', 'Consultation or class enquiry needs a clear route.', 'cta'),
      section('cta', 'high', 'Finish on the most truthful join-or-enquire action.', 'cta'),
      section('footer', 'low', 'Repeat essentials only.', 'footer'),
    ],
    recommendedTrustSystems: ['service-results', 'staff-credentials', 'rating-reviews', 'certifications'],
    recommendedGallerySystems: ['service-results', 'team', 'spaces'],
    recommendedTone: ['expert', 'modern-clean', 'direct', 'friendly'],
    degradationRules: [
      {
        id: 'fitness-no-booking',
        whenUnavailableActions: ['book-appointment', 'request-consultation'],
        guidance: 'If no enquiry or booking path exists, fall back to call and local visit actions.',
        suppress: ['join online claims', 'book class now language'],
        fallbackActions: ['call', 'get-directions', 'visit-website'],
      },
      {
        id: 'fitness-no-team',
        whenMissingSignals: ['image:team'],
        guidance: 'Do not imply visible coaches or practitioners if team material is missing.',
        suppress: ['trainer-led hero claims'],
        fallbackActions: ['call'],
      },
      {
        id: 'fitness-no-results',
        whenMissingSignals: ['image:results'],
        guidance: 'If no transformation proof exists, lean on facility quality, service clarity, and reviews.',
        suppress: ['before-after framing'],
        fallbackActions: ['get-directions', 'call'],
      },
    ],
    schemaHints: {
      preferredSchemaTypes: ['SportsActivityLocation', 'HealthClub', 'LocalBusiness'],
      prioritySignals: ['class or service list', 'coach credentials', 'opening hours', 'NAP consistency', 'review signals'],
      keywordPatterns: ['[category] [city]', '[class type] [city]', '[neighborhood] gym [city]'],
      doNotInvent: ['membership pricing', 'class timetable', 'trainer certifications', 'results claims'],
    },
  },
  'clinic-health': {
    sectorType: 'clinic-health',
    label: 'Clinic / Health / Wellbeing',
    description: 'Designed for clinics and health-led services where clarity, trust, and responsible claims are critical.',
    categoryKeywords: ['clinic', 'medical', 'health', 'physio', 'physiotherapy', 'dental', 'dentist', 'doctor', 'therapy'],
    offerKeywords: ['consultation', 'assessment', 'treatment', 'care', 'therapy', 'exam'],
    imageSignals: ['image:team', 'image:space', 'image:exterior'],
    primaryCtaPriority: ['request-consultation', 'book-appointment', 'call', 'get-directions'],
    secondaryCtaPriority: ['call', 'get-directions', 'visit-website', 'email'],
    conversionFocus: 'Lead with clarity and reassurance, then route users toward consultation or direct contact.',
    recommendedHeroType: 'trust-first',
    recommendedSections: [
      section('hero', 'high', 'The hero should establish clarity, legitimacy, and locality.', 'hero'),
      section('services', 'high', 'Users need to understand what conditions or needs you cover.', 'services'),
      section('trust', 'high', 'Credentials and careful trust signals are central.', 'credibility'),
      section('team', 'medium', 'Practitioner visibility supports confidence when verified.'),
      section('faq', 'medium', 'FAQ should answer practical patient or visitor questions.', 'faq'),
      section('location-contact', 'high', 'Directions and contact need to be unmissable.', 'cta'),
      section('booking', 'high', 'Consultation or appointment routes must stay clear and truthful.', 'cta'),
      section('cta', 'high', 'Close with the safest verified action.', 'cta'),
      section('footer', 'low', 'Use the footer for clean contact reinforcement.', 'footer'),
    ],
    recommendedTrustSystems: ['staff-credentials', 'certifications', 'rating-reviews', 'local-trust'],
    recommendedGallerySystems: ['spaces', 'team', 'exterior'],
    recommendedTone: ['clinical-clear', 'expert', 'direct'],
    degradationRules: [
      {
        id: 'clinic-no-booking',
        whenUnavailableActions: ['book-appointment', 'request-consultation'],
        guidance: 'If no verified booking or consultation path exists, fall back to call and avoid digital-booking language.',
        suppress: ['instant booking claims'],
        fallbackActions: ['call', 'get-directions', 'email'],
      },
      {
        id: 'clinic-no-team',
        whenMissingSignals: ['image:team'],
        guidance: 'Do not imply visible clinicians or named specialists without supporting material.',
        suppress: ['meet the doctor blocks', 'named clinician profiles'],
        fallbackActions: ['call'],
      },
      {
        id: 'clinic-no-credentials',
        whenMissingSignals: ['trust:credentials'],
        guidance: 'Avoid overplaying expertise claims if qualifications are not present in the source set.',
        suppress: ['specialist superlatives', 'credential-led hero copy'],
        fallbackActions: ['call', 'get-directions'],
      },
    ],
    schemaHints: {
      preferredSchemaTypes: ['MedicalClinic', 'MedicalBusiness', 'Dentist', 'LocalBusiness'],
      prioritySignals: ['NAP consistency', 'opening hours', 'service list', 'clinician names', 'medical specialty'],
      keywordPatterns: ['[service] clinic [city]', '[specialty] [city]', '[neighborhood] [category]'],
      doNotInvent: ['medical specialties', 'insurance support', 'certifications', 'same-day appointments'],
    },
  },
  'local-service': {
    sectorType: 'local-service',
    label: 'Local Service',
    description: 'Fallback profile for local businesses that do not clearly fit a more specific sector yet.',
    categoryKeywords: ['service', 'repair', 'contractor', 'agency', 'cleaning', 'plumber', 'electrician', 'local'],
    offerKeywords: ['service', 'quote', 'callout', 'estimate', 'appointment'],
    imageSignals: ['image:space', 'image:exterior', 'image:team'],
    primaryCtaPriority: ['call', 'request-consultation', 'get-directions', 'visit-website'],
    secondaryCtaPriority: ['get-directions', 'visit-website', 'email', 'call'],
    conversionFocus: 'Keep the page practical: clear service promise, local credibility, and one easy contact route.',
    recommendedHeroType: 'local-presence-first',
    recommendedSections: [
      section('hero', 'high', 'State what the business does and where it operates.', 'hero'),
      section('services', 'high', 'A fast service scan is usually the clearest route to relevance.', 'services'),
      section('trust', 'high', 'Local proof and review signals reduce uncertainty.', 'credibility'),
      section('about', 'medium', 'A short explanation helps if the category is broad.', 'about'),
      section('gallery', 'low', 'Only use visual proof if it adds trust.', 'gallery'),
      section('faq', 'medium', 'FAQ can handle availability, coverage, or process questions.', 'faq'),
      section('location-contact', 'high', 'Contact and service area should stay practical.', 'cta'),
      section('cta', 'high', 'Close with the safest truthful route to contact.', 'cta'),
      section('footer', 'low', 'Repeat the basics.', 'footer'),
    ],
    recommendedTrustSystems: ['rating-reviews', 'local-trust', 'years-in-business'],
    recommendedGallerySystems: ['spaces', 'exterior', 'team'],
    recommendedTone: ['direct', 'local-trust', 'friendly'],
    degradationRules: [
      {
        id: 'service-no-website',
        whenMissingPaths: ['contact.website'],
        guidance: 'If there is no verified website, keep the experience call- or directions-led.',
        suppress: ['visit-website emphasis'],
        fallbackActions: ['call', 'get-directions'],
      },
      {
        id: 'service-no-team',
        whenMissingSignals: ['image:team'],
        guidance: 'Do not force team-led trust if the source set does not support it.',
        suppress: ['team grids'],
        fallbackActions: ['call'],
      },
      {
        id: 'service-no-hours',
        whenMissingPaths: ['location.openingHours'],
        guidance: 'Avoid availability promises when opening hours or response windows are not verified.',
        suppress: ['same-day availability messaging'],
        fallbackActions: ['call', 'email'],
      },
    ],
    schemaHints: {
      preferredSchemaTypes: ['LocalBusiness', 'ProfessionalService'],
      prioritySignals: ['NAP consistency', 'service area', 'review signals', 'website presence', 'opening hours'],
      keywordPatterns: ['[service] [city]', '[neighborhood] [service]', '[category] near me'],
      doNotInvent: ['response times', 'pricing', 'coverage radius', 'certifications'],
    },
  },
};

export const SECTOR_RULE_ORDER: SectorType[] = [
  'restaurant',
  'cafe-bakery-takeaway',
  'personal-care',
  'retail-shop',
  'fitness-wellness',
  'clinic-health',
  'local-service',
];
