import type {
  VisualFamilyDefinition,
  VisualFamilyId,
} from '../../types/visual-engine';

export const VISUAL_FAMILIES: Record<VisualFamilyId, VisualFamilyDefinition> = {
  'food-warm-editorial': {
    familyId: 'food-warm-editorial',
    label: 'Food Warm Editorial',
    description: 'Warm, tactile, appetite-led direction for food businesses with enough imagery to feel rich without becoming noisy.',
    personality: 'Premium-casual, sensory, local, and editorial without becoming precious.',
    suitedSectors: ['restaurant', 'cafe-bakery-takeaway'],
    bestFor: [
      'Restaurants with strong dish photography',
      'Cafes and bakeries with warmth and product appeal',
      'Brands that need appetite, locality, and trust to land fast',
    ],
    avoidWhen: [
      'Image quality is weak or very sparse',
      'The business needs a clinical or highly restrained tone',
      'Trust must lean more on credentials than atmosphere',
    ],
    toneAffinities: ['premium-casual', 'warm', 'local-trust', 'friendly'],
    luxuryAffinities: ['high', 'editorial'],
    preferredColorTemperature: ['warm', 'neutral'],
    preferredImageAbundance: ['high', 'medium'],
    palette: {
      background: '#2a140e',
      backgroundAlt: '#1b0f0c',
      surface: 'rgba(43, 21, 14, 0.84)',
      surfaceSoft: 'rgba(69, 33, 19, 0.56)',
      textPrimary: '#f7ead8',
      textSecondary: 'rgba(247, 234, 216, 0.76)',
      textMuted: 'rgba(247, 234, 216, 0.54)',
      accentPrimary: '#f3a229',
      accentSecondary: '#c5482e',
      borderSoft: 'rgba(247, 234, 216, 0.16)',
      borderStrong: 'rgba(243, 162, 41, 0.36)',
      overlayStrong: 'rgba(17, 9, 7, 0.68)',
      overlaySoft: 'rgba(243, 162, 41, 0.14)',
      ctaPrimaryBackground: '#f3a229',
      ctaPrimaryText: '#26120d',
      ctaSecondaryBorder: 'rgba(247, 234, 216, 0.22)',
      ctaSecondaryText: '#f7ead8',
      chipBackground: 'rgba(243, 162, 41, 0.12)',
      chipText: '#ffd17b',
    },
    typography: {
      displayFamily: "'Instrument Serif', serif",
      bodyFamily: "'Bricolage Grotesque Variable', sans-serif",
      combination: 'serif-sans',
      displayTone: 'Expressive serif headlines with grounded sans body copy.',
      h1Weight: 500,
      h2Weight: 500,
      h3Weight: 600,
      bodyWeight: 430,
      maxHeroLineLength: '13ch',
      bodyMeasure: '62ch',
    },
    spacing: {
      density: 'balanced',
      sectionGap: 'clamp(5rem, 10vw, 8.75rem)',
      contentGap: 'clamp(1.2rem, 2.5vw, 2rem)',
      cardGap: 'clamp(1rem, 2vw, 1.5rem)',
      heroGap: 'clamp(1.5rem, 3vw, 2.5rem)',
      containerWidth: 'min(100% - 1.6rem, 90rem)',
    },
    hero: {
      recommendedHeroType: 'food-first',
      layoutMood: 'Image-led split or poster composition with clear appetite cue.',
      mediaBalance: 'Large hero frame with one supporting food detail max.',
      overlayTreatment: 'Warm cinematic overlay with tactile captioning.',
      headlineApproach: 'Keep the headline short and sensory, then explain locality fast.',
      currentHeroVariant: 'immersive-poster',
    },
    cta: {
      primaryStyle: 'accent-solid',
      secondaryStyle: 'ghost-outline',
      weightBalance: 'clear-primary',
      buttonShape: 'pill',
      maxVisibleActions: 2,
    },
    cards: {
      featuredItemStyle: 'editorial-frame',
      serviceCardStyle: 'luxe-panel',
      trustCardStyle: 'trust-panel',
      infoCardStyle: 'luxe-panel',
      highlightCardStyle: 'editorial-frame',
      currentServicesVariant: 'editorial-rows',
    },
    gallery: {
      recommendedGallerySystems: ['dishes', 'ambience', 'exterior'],
      layout: 'frames-mosaic',
      cropBias: 'mixed',
      maxImages: 5,
      currentGalleryVariant: 'frames-mosaic',
    },
    trust: {
      recommendedTrustSystems: ['rating-reviews', 'menu-signatures', 'local-trust'],
      style: 'rating-panel',
      emphasis: 'Ratings and signature-item proof should land before deeper story.',
      contactCardTone: 'Warm reassurance with local specifics.',
    },
    motion: {
      entranceStyle: 'cinematic-float',
      hoverStyle: 'gentle-rise',
      ambientStyle: 'cinematic-float',
      motionIntensity: 'medium',
    },
    degradationRules: [
      {
        id: 'warm-food-no-brand-colors',
        whenNoBrandColors: true,
        guidance: 'If no business colors are confirmed, stay on the family core palette and avoid invented color flourishes.',
        adjustments: ['use family base palette', 'avoid color-coded menu accents'],
      },
      {
        id: 'warm-food-low-images',
        whenLowImageCount: 3,
        guidance: 'If food imagery is limited, collapse to a single-image hero and a tighter gallery.',
        adjustments: ['single hero image', 'max 3 gallery frames', 'promote rating/trust panel earlier'],
      },
      {
        id: 'warm-food-no-exterior',
        whenMissingSignals: ['image:exterior'],
        guidance: 'If no exterior photo exists, keep the gallery dish-led and let location trust come from maps/contact blocks.',
        adjustments: ['remove storefront framing', 'promote address/contact card'],
      },
    ],
    currentCtaVariant: 'book-consult',
  },
  'local-service-premium': {
    familyId: 'local-service-premium',
    label: 'Local Service Premium',
    description: 'Practical premium direction for service-led local businesses that need clarity, trust, and tidy conversion.',
    personality: 'Grounded, confident, and polished without over-styling.',
    suitedSectors: ['local-service', 'fitness-wellness', 'personal-care'],
    bestFor: [
      'Local services where clarity beats spectacle',
      'Fitness and grooming businesses without luxe editorial assets',
      'Businesses with decent trust signals but medium visual richness',
    ],
    avoidWhen: [
      'The brand wants dramatic dark luxury',
      'The business is heavily product-led',
      'The brand has strong food or clinical cues instead',
    ],
    toneAffinities: ['local-trust', 'direct', 'friendly', 'expert'],
    luxuryAffinities: ['elevated', 'high'],
    preferredColorTemperature: ['neutral', 'warm'],
    preferredImageAbundance: ['medium', 'low'],
    palette: {
      background: '#171312',
      backgroundAlt: '#111011',
      surface: 'rgba(28, 24, 23, 0.88)',
      surfaceSoft: 'rgba(44, 38, 37, 0.58)',
      textPrimary: '#f3ede4',
      textSecondary: 'rgba(243, 237, 228, 0.78)',
      textMuted: 'rgba(243, 237, 228, 0.58)',
      accentPrimary: '#d5ab79',
      accentSecondary: '#8c6b52',
      borderSoft: 'rgba(243, 237, 228, 0.14)',
      borderStrong: 'rgba(213, 171, 121, 0.32)',
      overlayStrong: 'rgba(10, 9, 10, 0.66)',
      overlaySoft: 'rgba(213, 171, 121, 0.12)',
      ctaPrimaryBackground: '#d5ab79',
      ctaPrimaryText: '#161210',
      ctaSecondaryBorder: 'rgba(243, 237, 228, 0.2)',
      ctaSecondaryText: '#f3ede4',
      chipBackground: 'rgba(213, 171, 121, 0.1)',
      chipText: '#efd4a9',
    },
    typography: {
      displayFamily: "'Bricolage Grotesque Variable', sans-serif",
      bodyFamily: "'Bricolage Grotesque Variable', sans-serif",
      combination: 'sans-sans',
      displayTone: 'Confident sans-led hierarchy with occasional serif reserved for emphasis later.',
      h1Weight: 650,
      h2Weight: 620,
      h3Weight: 610,
      bodyWeight: 430,
      maxHeroLineLength: '12ch',
      bodyMeasure: '60ch',
    },
    spacing: {
      density: 'balanced',
      sectionGap: 'clamp(4.5rem, 8vw, 7rem)',
      contentGap: 'clamp(1.1rem, 2vw, 1.75rem)',
      cardGap: 'clamp(0.9rem, 1.8vw, 1.25rem)',
      heroGap: 'clamp(1.25rem, 2.5vw, 2rem)',
      containerWidth: 'min(100% - 1.5rem, 86rem)',
    },
    hero: {
      recommendedHeroType: 'service-first',
      layoutMood: 'Clean split or monolith composition with trust-first support panel.',
      mediaBalance: 'Prefer one main image or environment frame over busy stacks.',
      overlayTreatment: 'Restrained overlay and practical fact strip.',
      headlineApproach: 'State the offer clearly, then support with location and trust.',
      currentHeroVariant: 'cinematic-split',
    },
    cta: {
      primaryStyle: 'dark-solid',
      secondaryStyle: 'ghost-outline',
      weightBalance: 'clear-primary',
      buttonShape: 'pill',
      maxVisibleActions: 2,
    },
    cards: {
      featuredItemStyle: 'luxe-panel',
      serviceCardStyle: 'clean-elevated',
      trustCardStyle: 'trust-panel',
      infoCardStyle: 'minimal-border',
      highlightCardStyle: 'clean-elevated',
      currentServicesVariant: 'signature-grid',
    },
    gallery: {
      recommendedGallerySystems: ['spaces', 'team', 'service-results'],
      layout: 'structured-grid',
      cropBias: 'landscape-first',
      maxImages: 4,
      currentGalleryVariant: 'atmosphere-carousel',
    },
    trust: {
      recommendedTrustSystems: ['rating-reviews', 'local-trust', 'years-in-business'],
      style: 'contact-trust-panel',
      emphasis: 'Contact clarity and reassurance should sit close together.',
      contactCardTone: 'Practical and trustworthy.',
    },
    motion: {
      entranceStyle: 'clean-slide',
      hoverStyle: 'gentle-rise',
      ambientStyle: 'minimal',
      motionIntensity: 'low',
    },
    degradationRules: [
      {
        id: 'service-premium-low-images',
        whenLowImageCount: 2,
        guidance: 'If image material is thin, bias the layout toward service and trust cards rather than decorative media.',
        adjustments: ['single visual anchor', 'text-led cards', 'reduce gallery footprint'],
      },
      {
        id: 'service-premium-no-brand-colors',
        whenNoBrandColors: true,
        guidance: 'If brand color input is weak, use neutral charcoal and bronze accents only.',
        adjustments: ['neutral palette lock', 'avoid multi-accent surfaces'],
      },
      {
        id: 'service-premium-incomplete-brief',
        whenIncompleteBrief: true,
        guidance: 'If the brief is still incomplete, keep the direction restrained and utility-led.',
        adjustments: ['trust-first hero support', 'reduce decorative motion'],
      },
    ],
    currentCtaVariant: 'visit-studio',
  },
  'retail-clean-modern': {
    familyId: 'retail-clean-modern',
    label: 'Retail Clean Modern',
    description: 'A bright, controlled product-led system for shops and modern retail brands.',
    personality: 'Clean, composed, and conversion-friendly with enough polish to feel considered.',
    suitedSectors: ['retail-shop'],
    bestFor: [
      'Retail and boutique businesses with product imagery',
      'Brands that need a cleaner, less atmospheric conversion path',
      'Businesses with modern-clean tone cues',
    ],
    avoidWhen: [
      'The brand depends on strong warmth and heavy ambience',
      'The business is highly clinical or authority-led',
      'There is no product or shelf imagery to support it',
    ],
    toneAffinities: ['modern-clean', 'direct', 'boutique'],
    luxuryAffinities: ['elevated', 'high'],
    preferredColorTemperature: ['neutral', 'cool'],
    preferredImageAbundance: ['high', 'medium'],
    palette: {
      background: '#f5f4f0',
      backgroundAlt: '#ebe9e2',
      surface: 'rgba(255, 255, 255, 0.84)',
      surfaceSoft: 'rgba(255, 255, 255, 0.62)',
      textPrimary: '#1f2326',
      textSecondary: 'rgba(31, 35, 38, 0.74)',
      textMuted: 'rgba(31, 35, 38, 0.52)',
      accentPrimary: '#1d6a69',
      accentSecondary: '#9d7b58',
      borderSoft: 'rgba(31, 35, 38, 0.1)',
      borderStrong: 'rgba(29, 106, 105, 0.22)',
      overlayStrong: 'rgba(17, 21, 23, 0.52)',
      overlaySoft: 'rgba(29, 106, 105, 0.08)',
      ctaPrimaryBackground: '#1d6a69',
      ctaPrimaryText: '#f5f4f0',
      ctaSecondaryBorder: 'rgba(31, 35, 38, 0.18)',
      ctaSecondaryText: '#1f2326',
      chipBackground: 'rgba(29, 106, 105, 0.08)',
      chipText: '#1d6a69',
    },
    typography: {
      displayFamily: "'Bricolage Grotesque Variable', sans-serif",
      bodyFamily: "'Bricolage Grotesque Variable', sans-serif",
      combination: 'sans-sans',
      displayTone: 'Precise sans stack with stronger contrast in scale than in ornament.',
      h1Weight: 640,
      h2Weight: 620,
      h3Weight: 600,
      bodyWeight: 420,
      maxHeroLineLength: '11ch',
      bodyMeasure: '58ch',
    },
    spacing: {
      density: 'airy',
      sectionGap: 'clamp(5rem, 9vw, 8rem)',
      contentGap: 'clamp(1.25rem, 2vw, 1.9rem)',
      cardGap: 'clamp(1rem, 1.8vw, 1.4rem)',
      heroGap: 'clamp(1.4rem, 2.4vw, 2rem)',
      containerWidth: 'min(100% - 2rem, 88rem)',
    },
    hero: {
      recommendedHeroType: 'product-first',
      layoutMood: 'Product-led monolith with clean negative space and restrained supporting panels.',
      mediaBalance: 'One strong product or environment image plus compact proof.',
      overlayTreatment: 'Minimal overlays, sharper edges, cleaner text framing.',
      headlineApproach: 'Keep copy direct and product-oriented.',
      currentHeroVariant: 'monolith-stack',
    },
    cta: {
      primaryStyle: 'dark-solid',
      secondaryStyle: 'clean-outline',
      weightBalance: 'clear-primary',
      buttonShape: 'rounded-rect',
      maxVisibleActions: 2,
    },
    cards: {
      featuredItemStyle: 'clean-elevated',
      serviceCardStyle: 'clean-elevated',
      trustCardStyle: 'minimal-border',
      infoCardStyle: 'minimal-border',
      highlightCardStyle: 'editorial-frame',
      currentServicesVariant: 'signature-grid',
    },
    gallery: {
      recommendedGallerySystems: ['products', 'spaces', 'exterior'],
      layout: 'structured-grid',
      cropBias: 'portrait-first',
      maxImages: 6,
      currentGalleryVariant: 'frames-mosaic',
    },
    trust: {
      recommendedTrustSystems: ['product-quality', 'rating-reviews', 'local-trust'],
      style: 'reassurance-cards',
      emphasis: 'Use simple, scannable product and visit reassurance instead of heavy atmospheric proof.',
      contactCardTone: 'Practical and clean.',
    },
    motion: {
      entranceStyle: 'clean-slide',
      hoverStyle: 'clean-slide',
      ambientStyle: 'minimal',
      motionIntensity: 'low',
    },
    degradationRules: [
      {
        id: 'retail-clean-low-products',
        whenMissingSignals: ['image:product'],
        guidance: 'If product imagery is weak, shift to a cleaner store-presence layout and reduce product-card density.',
        adjustments: ['promote location/contact', 'smaller gallery', 'fewer product cards'],
      },
      {
        id: 'retail-clean-no-brand-colors',
        whenNoBrandColors: true,
        guidance: 'If brand colors are unavailable, hold to neutral stone and a single cool accent.',
        adjustments: ['single accent only', 'neutral surfaces'],
      },
    ],
    currentCtaVariant: 'visit-studio',
  },
  'clinic-calm-trust': {
    familyId: 'clinic-calm-trust',
    label: 'Clinic Calm Trust',
    description: 'Calm, legible, trust-led direction for clinical and wellbeing contexts where reassurance matters more than spectacle.',
    personality: 'Clear, soft, professional, and quietly confident.',
    suitedSectors: ['clinic-health'],
    bestFor: [
      'Clinics and health-led services',
      'Businesses that need calm clarity and trust-first hierarchy',
      'Contexts where readability and restraint matter most',
    ],
    avoidWhen: [
      'The business depends on rich food or retail imagery',
      'The brand wants heavy dark luxury',
      'The sector is more playful or appetite-led',
    ],
    toneAffinities: ['clinical-clear', 'expert', 'direct'],
    luxuryAffinities: ['elevated', 'high'],
    preferredColorTemperature: ['cool', 'neutral'],
    preferredImageAbundance: ['medium', 'low'],
    palette: {
      background: '#edf4f3',
      backgroundAlt: '#dfeae7',
      surface: 'rgba(255, 255, 255, 0.9)',
      surfaceSoft: 'rgba(255, 255, 255, 0.72)',
      textPrimary: '#183334',
      textSecondary: 'rgba(24, 51, 52, 0.76)',
      textMuted: 'rgba(24, 51, 52, 0.56)',
      accentPrimary: '#2b7a78',
      accentSecondary: '#9ab8b6',
      borderSoft: 'rgba(24, 51, 52, 0.1)',
      borderStrong: 'rgba(43, 122, 120, 0.22)',
      overlayStrong: 'rgba(16, 39, 40, 0.48)',
      overlaySoft: 'rgba(43, 122, 120, 0.08)',
      ctaPrimaryBackground: '#2b7a78',
      ctaPrimaryText: '#edf4f3',
      ctaSecondaryBorder: 'rgba(24, 51, 52, 0.18)',
      ctaSecondaryText: '#183334',
      chipBackground: 'rgba(43, 122, 120, 0.08)',
      chipText: '#2b7a78',
    },
    typography: {
      displayFamily: "'Bricolage Grotesque Variable', sans-serif",
      bodyFamily: "'Bricolage Grotesque Variable', sans-serif",
      combination: 'sans-sans',
      displayTone: 'Calm sans hierarchy with low drama and high legibility.',
      h1Weight: 620,
      h2Weight: 600,
      h3Weight: 580,
      bodyWeight: 420,
      maxHeroLineLength: '12ch',
      bodyMeasure: '64ch',
    },
    spacing: {
      density: 'airy',
      sectionGap: 'clamp(5rem, 9vw, 8rem)',
      contentGap: 'clamp(1.15rem, 2vw, 1.9rem)',
      cardGap: 'clamp(0.95rem, 1.8vw, 1.4rem)',
      heroGap: 'clamp(1.25rem, 2.4vw, 2rem)',
      containerWidth: 'min(100% - 2rem, 88rem)',
    },
    hero: {
      recommendedHeroType: 'trust-first',
      layoutMood: 'Calm monolith or split layout with strong trust and contact framing.',
      mediaBalance: 'Media should support reassurance, not dominate the screen.',
      overlayTreatment: 'Soft glass-like surfaces and restrained overlays.',
      headlineApproach: 'State the offer clearly and avoid poetic language.',
      currentHeroVariant: 'monolith-stack',
    },
    cta: {
      primaryStyle: 'calm-solid',
      secondaryStyle: 'clean-outline',
      weightBalance: 'clear-primary',
      buttonShape: 'rounded-rect',
      maxVisibleActions: 2,
    },
    cards: {
      featuredItemStyle: 'trust-panel',
      serviceCardStyle: 'clean-elevated',
      trustCardStyle: 'trust-panel',
      infoCardStyle: 'clean-elevated',
      highlightCardStyle: 'minimal-border',
      currentServicesVariant: 'signature-grid',
    },
    gallery: {
      recommendedGallerySystems: ['spaces', 'team', 'exterior'],
      layout: 'proof-strip',
      cropBias: 'landscape-first',
      maxImages: 4,
      currentGalleryVariant: 'atmosphere-carousel',
    },
    trust: {
      recommendedTrustSystems: ['staff-credentials', 'certifications', 'rating-reviews'],
      style: 'credential-stack',
      emphasis: 'Credentials and reassurance should land before any dramatic imagery.',
      contactCardTone: 'Calm and informative.',
    },
    motion: {
      entranceStyle: 'gentle-rise',
      hoverStyle: 'minimal',
      ambientStyle: 'minimal',
      motionIntensity: 'low',
    },
    degradationRules: [
      {
        id: 'clinic-no-team-visuals',
        whenMissingSignals: ['image:team'],
        guidance: 'If no team imagery exists, keep the visual system space-led and reinforce trust through credentials and contact.',
        adjustments: ['space-led gallery', 'credential-first trust block'],
      },
      {
        id: 'clinic-no-brand-colors',
        whenNoBrandColors: true,
        guidance: 'If brand colors are not known, stay with calm teal-neutral defaults.',
        adjustments: ['teal-neutral palette lock', 'remove decorative accents'],
      },
      {
        id: 'clinic-incomplete-brief',
        whenIncompleteBrief: true,
        guidance: 'If the brief is incomplete, keep sections simpler and reduce visual flourish.',
        adjustments: ['fewer layered surfaces', 'single-column trust card emphasis'],
      },
    ],
    currentCtaVariant: 'visit-studio',
  },
  'dark-boutique-luxury': {
    familyId: 'dark-boutique-luxury',
    label: 'Dark Boutique Luxury',
    description: 'A darker, richer family for boutique brands that have enough visual strength and premium cues to carry it.',
    personality: 'Atmospheric, cinematic, and deliberate, with strong contrast and a more exclusive feel.',
    suitedSectors: ['personal-care', 'retail-shop', 'fitness-wellness'],
    bestFor: [
      'Boutique personal-care brands',
      'Luxury-leaning retail or wellness businesses',
      'Businesses with strong imagery and higher perceived positioning',
    ],
    avoidWhen: [
      'The brief is incomplete or trust is still fragile',
      'The business depends on clinical calm',
      'The image library is weak or inconsistent',
    ],
    toneAffinities: ['boutique', 'modern-clean', 'premium-casual', 'expert'],
    luxuryAffinities: ['high', 'editorial'],
    preferredColorTemperature: ['neutral', 'cool', 'warm'],
    preferredImageAbundance: ['high', 'medium'],
    palette: {
      background: '#0f0f12',
      backgroundAlt: '#17161b',
      surface: 'rgba(23, 22, 27, 0.9)',
      surfaceSoft: 'rgba(36, 33, 40, 0.64)',
      textPrimary: '#f3efe8',
      textSecondary: 'rgba(243, 239, 232, 0.76)',
      textMuted: 'rgba(243, 239, 232, 0.56)',
      accentPrimary: '#c9a56b',
      accentSecondary: '#8362b3',
      borderSoft: 'rgba(243, 239, 232, 0.12)',
      borderStrong: 'rgba(201, 165, 107, 0.32)',
      overlayStrong: 'rgba(7, 7, 10, 0.72)',
      overlaySoft: 'rgba(131, 98, 179, 0.1)',
      ctaPrimaryBackground: '#c9a56b',
      ctaPrimaryText: '#141217',
      ctaSecondaryBorder: 'rgba(243, 239, 232, 0.18)',
      ctaSecondaryText: '#f3efe8',
      chipBackground: 'rgba(201, 165, 107, 0.1)',
      chipText: '#ecd4a4',
    },
    typography: {
      displayFamily: "'Instrument Serif', serif",
      bodyFamily: "'Bricolage Grotesque Variable', sans-serif",
      combination: 'serif-sans',
      displayTone: 'High-contrast display serif with cleaner sans support.',
      h1Weight: 520,
      h2Weight: 520,
      h3Weight: 620,
      bodyWeight: 430,
      maxHeroLineLength: '11ch',
      bodyMeasure: '60ch',
    },
    spacing: {
      density: 'airy',
      sectionGap: 'clamp(5.25rem, 10vw, 8.5rem)',
      contentGap: 'clamp(1.2rem, 2vw, 1.9rem)',
      cardGap: 'clamp(1rem, 2vw, 1.5rem)',
      heroGap: 'clamp(1.5rem, 3vw, 2.3rem)',
      containerWidth: 'min(100% - 1.8rem, 92rem)',
    },
    hero: {
      recommendedHeroType: 'editorial-first',
      layoutMood: 'Poster-like, media-heavy, and layered with controlled drama.',
      mediaBalance: 'Strong hero visual with minimal supporting frames.',
      overlayTreatment: 'Deep contrast overlays and luxe captions.',
      headlineApproach: 'Short, premium, and more sculpted than descriptive.',
      currentHeroVariant: 'immersive-poster',
    },
    cta: {
      primaryStyle: 'accent-solid',
      secondaryStyle: 'ghost-outline',
      weightBalance: 'clear-primary',
      buttonShape: 'pill',
      maxVisibleActions: 2,
    },
    cards: {
      featuredItemStyle: 'editorial-frame',
      serviceCardStyle: 'luxe-panel',
      trustCardStyle: 'trust-panel',
      infoCardStyle: 'minimal-border',
      highlightCardStyle: 'editorial-frame',
      currentServicesVariant: 'editorial-rows',
    },
    gallery: {
      recommendedGallerySystems: ['service-results', 'products', 'ambience', 'team'],
      layout: 'poster-strip',
      cropBias: 'portrait-first',
      maxImages: 5,
      currentGalleryVariant: 'frames-mosaic',
    },
    trust: {
      recommendedTrustSystems: ['service-results', 'product-quality', 'rating-reviews'],
      style: 'review-columns',
      emphasis: 'Keep trust elevated and selective rather than stacked with too many badges.',
      contactCardTone: 'Selective and premium.',
    },
    motion: {
      entranceStyle: 'cinematic-float',
      hoverStyle: 'gentle-rise',
      ambientStyle: 'cinematic-float',
      motionIntensity: 'medium',
    },
    degradationRules: [
      {
        id: 'boutique-low-images',
        whenLowImageCount: 4,
        guidance: 'If imagery is not rich enough, do not force the dark boutique route into a dramatic media stack.',
        adjustments: ['downgrade to cleaner hero', 'reduce gallery ambition', 'lean on trust cards'],
      },
      {
        id: 'boutique-no-brand-colors',
        whenNoBrandColors: true,
        guidance: 'If brand colors are weak, stay with dark neutrals and one metallic accent.',
        adjustments: ['single metallic accent', 'no multi-color highlights'],
      },
      {
        id: 'boutique-incomplete-brief',
        whenIncompleteBrief: true,
        guidance: 'If the brief still has material gaps, prefer a restrained premium interpretation over high-drama presentation.',
        adjustments: ['restrained hero copy framing', 'fewer overlays'],
      },
    ],
    currentCtaVariant: 'book-consult',
  },
  'neutral-reusable': {
    familyId: 'neutral-reusable',
    label: 'Neutral Reusable',
    description: 'Safe but still intentional fallback family for businesses with lighter data, lighter assets, or mixed signals.',
    personality: 'Clean, adaptable, and low-risk.',
    suitedSectors: ['restaurant', 'cafe-bakery-takeaway', 'personal-care', 'retail-shop', 'fitness-wellness', 'clinic-health', 'local-service'],
    bestFor: [
      'Mixed-signal businesses',
      'Incomplete briefs',
      'Businesses where structure matters more than a strong stylistic claim for now',
    ],
    avoidWhen: [
      'The brand clearly has a stronger sector and asset fit',
      'The image library and brand direction are already rich enough for a more distinctive family',
    ],
    toneAffinities: ['direct', 'friendly', 'local-trust', 'modern-clean'],
    luxuryAffinities: ['elevated', 'high', 'editorial'],
    preferredColorTemperature: ['neutral', 'warm', 'cool'],
    preferredImageAbundance: ['low', 'medium', 'high'],
    palette: {
      background: '#141517',
      backgroundAlt: '#1c1f22',
      surface: 'rgba(27, 30, 34, 0.88)',
      surfaceSoft: 'rgba(40, 45, 50, 0.62)',
      textPrimary: '#f2efe9',
      textSecondary: 'rgba(242, 239, 233, 0.76)',
      textMuted: 'rgba(242, 239, 233, 0.56)',
      accentPrimary: '#9b8c77',
      accentSecondary: '#5d7688',
      borderSoft: 'rgba(242, 239, 233, 0.12)',
      borderStrong: 'rgba(155, 140, 119, 0.3)',
      overlayStrong: 'rgba(10, 12, 15, 0.64)',
      overlaySoft: 'rgba(155, 140, 119, 0.08)',
      ctaPrimaryBackground: '#9b8c77',
      ctaPrimaryText: '#141517',
      ctaSecondaryBorder: 'rgba(242, 239, 233, 0.18)',
      ctaSecondaryText: '#f2efe9',
      chipBackground: 'rgba(155, 140, 119, 0.08)',
      chipText: '#d9c8af',
    },
    typography: {
      displayFamily: "'Bricolage Grotesque Variable', sans-serif",
      bodyFamily: "'Bricolage Grotesque Variable', sans-serif",
      combination: 'sans-sans',
      displayTone: 'Straightforward sans-led system with minimal stylistic risk.',
      h1Weight: 620,
      h2Weight: 600,
      h3Weight: 580,
      bodyWeight: 420,
      maxHeroLineLength: '12ch',
      bodyMeasure: '60ch',
    },
    spacing: {
      density: 'balanced',
      sectionGap: 'clamp(4.5rem, 8vw, 7.5rem)',
      contentGap: 'clamp(1rem, 2vw, 1.75rem)',
      cardGap: 'clamp(0.9rem, 1.8vw, 1.3rem)',
      heroGap: 'clamp(1.2rem, 2.4vw, 1.9rem)',
      containerWidth: 'min(100% - 1.6rem, 88rem)',
    },
    hero: {
      recommendedHeroType: 'local-presence-first',
      layoutMood: 'Balanced split with practical proof and restrained media.',
      mediaBalance: 'One main visual, minimal support.',
      overlayTreatment: 'Subtle overlays and simpler fact strips.',
      headlineApproach: 'Lead with clarity and keep ornament low.',
      currentHeroVariant: 'cinematic-split',
    },
    cta: {
      primaryStyle: 'dark-solid',
      secondaryStyle: 'ghost-outline',
      weightBalance: 'clear-primary',
      buttonShape: 'pill',
      maxVisibleActions: 2,
    },
    cards: {
      featuredItemStyle: 'clean-elevated',
      serviceCardStyle: 'clean-elevated',
      trustCardStyle: 'trust-panel',
      infoCardStyle: 'minimal-border',
      highlightCardStyle: 'clean-elevated',
      currentServicesVariant: 'signature-grid',
    },
    gallery: {
      recommendedGallerySystems: ['ambience', 'spaces', 'products', 'dishes'],
      layout: 'structured-grid',
      cropBias: 'mixed',
      maxImages: 4,
      currentGalleryVariant: 'atmosphere-carousel',
    },
    trust: {
      recommendedTrustSystems: ['rating-reviews', 'local-trust'],
      style: 'contact-trust-panel',
      emphasis: 'Keep trust useful and scannable.',
      contactCardTone: 'Practical and neutral.',
    },
    motion: {
      entranceStyle: 'gentle-rise',
      hoverStyle: 'minimal',
      ambientStyle: 'minimal',
      motionIntensity: 'low',
    },
    degradationRules: [
      {
        id: 'neutral-no-brand-colors',
        whenNoBrandColors: true,
        guidance: 'If the brand has no usable color cues, stay neutral and rely on hierarchy rather than color variation.',
        adjustments: ['single accent only', 'neutral surfaces'],
      },
      {
        id: 'neutral-low-images',
        whenLowImageCount: 2,
        guidance: 'If imagery is limited, keep the hero simple and avoid elaborate gallery expectations.',
        adjustments: ['single hero visual', 'optional gallery suppression'],
      },
      {
        id: 'neutral-incomplete-brief',
        whenIncompleteBrief: true,
        guidance: 'If the brief is incomplete, keep spacing generous and visual storytelling restrained.',
        adjustments: ['reduce decorative layers', 'trust-first ordering'],
      },
    ],
    currentCtaVariant: 'visit-studio',
  },
};

export const VISUAL_FAMILY_ORDER: VisualFamilyId[] = [
  'food-warm-editorial',
  'local-service-premium',
  'retail-clean-modern',
  'clinic-calm-trust',
  'dark-boutique-luxury',
  'neutral-reusable',
];
